CREATE DATABASE IF NOT EXISTS shortener;
CREATE TABLE  `shortener`.`urls` (
`id` MEDIUMINT( 100 ) NOT NULL AUTO_INCREMENT COMMENT  'idx',
`hash` CHAR( 8 ) NOT NULL ,
`url` CHAR( 255 ) NOT NULL ,
`created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
PRIMARY KEY (  `id` ) ,
UNIQUE (
`id` 
),
CONSTRAINT UNIQUE  (`hash`)
) ENGINE = MYISAM ;